// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TuWvSNIpTzKy1oLGuI_12mtN_8-0VIo',
    appId: '1:780562670814:web:f8197a13bda89b5ccf0e4f',
    messagingSenderId: '780562670814',
    projectId: 'qualidade-produtividade-app',
    authDomain: 'qualidade-produtividade-app.firebaseapp.com',
    storageBucket: 'qualidade-produtividade-app.firebasestorage.app',
    measurementId: 'G-3HH0XJHMVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7wlxZHvfjLrJ-BYThAKzSfcyypxRWSc',
    appId: '1:780562670814:android:5a1f63604c3e7695cf0e4f',
    messagingSenderId: '780562670814',
    projectId: 'qualidade-produtividade-app',
    storageBucket: 'qualidade-produtividade-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjvkQ6LqymFO1PUQEdBwVG_op4QZ7j4Gg',
    appId: '1:780562670814:ios:43c643349d9249ddcf0e4f',
    messagingSenderId: '780562670814',
    projectId: 'qualidade-produtividade-app',
    storageBucket: 'qualidade-produtividade-app.firebasestorage.app',
    iosBundleId: 'com.example.pp',
  );
}
